### ISSUE TITLE
Diagrams not rendering in Edge 

### ISSUE THREAD

**Issue by thoni56** [structurizr/lite#133]
### Description

Using Microsoft Edge Version 123.0.2420.97 diagrams are not rendered. The left panel with the list of diagrams are shown, but the pane where the selected diagram should be shown is blank. This does not occur on the uploaded version at https://structurizr.com.

The console shows some errors which do not show up in Chrome (where rendering works without errors).

### Steps to reproduce

1. Start Structurizr/Lite on a workspace with diagrams.
2. Use Microsoft Edge and navigate to the diagram view.

### Screenshot

![image](https://github.com/structurizr/lite/assets/204496/94f3a97d-1a89-4336-8a46-7c7664724f9c)
![image](https://github.com/structurizr/lite/assets/204496/0714ec98-3c9f-4b06-b98d-2c94bee6cd0f)

### Severity

Major

### Priority

I have no budget and there's no rush, please fix this for free

### More information

This is a text version of the console log in Edge:

14Third-party cookie will be blocked. Learn more in the Issues tab.
8Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure font '<URL>'. This request has been blocked; the content must be served over HTTPS.
diagrams:3528 Uncaught TypeError: structurizr.diagram.reset is not a function
diagrams:2924  Uncaught TypeError: structurizr.diagram.reset is not a function
    at changeView (diagrams:2924:29)
    at diagramCreated (diagrams:2871:13)
web-client-content-script.js:2  Uncaught (in promise) Error: Orphaned iframed
    at zn (web-client-content-script.js:2:284457)
    at Yn (web-client-content-script.js:2:284542)
    at web-client-content-script.js:2:382523
    at web-client-content-script.js:2:383607
    at Object.stateSync (web-client-content-script.js:2:383613)
    at web-client-content-script.js:2:382443
    at d (web-client-content-script.js:2:189771)
    at Generator.<anonymous> (web-client-content-script.js:2:191108)
    at Generator.next (web-client-content-script.js:2:190134)
    at b (web-client-content-script.js:2:195761)
web-client-content-script.js:2  Uncaught (in promise) Error: Orphaned iframed
    at zn (web-client-content-script.js:2:284457)
    at Yn (web-client-content-script.js:2:284542)
    at web-client-content-script.js:2:382523
    at web-client-content-script.js:2:383607
    at Object.stateSync (web-client-content-script.js:2:383613)
    at web-client-content-script.js:2:382443
    at d (web-client-content-script.js:2:189771)
    at Generator.<anonymous> (web-client-content-script.js:2:191108)
    at Generator.next (web-client-content-script.js:2:190134)
    at b (web-client-content-script.js:2:195761)
diagrams:3528 Uncaught TypeError: Cannot read properties of undefined (reading 'type')
structurizr-diagram.js:1469  Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at setZoomAndMargins (structurizr-diagram.js:1469:25)
    at structurizr.ui.Diagram.zoomToWidthOrHeight (structurizr-diagram.js:3765:9)
    at diagrams:3254:33
    at dispatch (jquery-3.6.3.min.js:2:43336)
    at y.handle (jquery-3.6.3.min.js:2:41320)
diagrams:3528 Uncaught TypeError: Cannot read properties of undefined (reading 'type')
structurizr-diagram.js:1469  Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at setZoomAndMargins (structurizr-diagram.js:1469:25)
    at structurizr.ui.Diagram.zoomToWidthOrHeight (structurizr-diagram.js:3765:9)
    at diagrams:3254:33
    at dispatch (jquery-3.6.3.min.js:2:43336)
    at y.handle (jquery-3.6.3.min.js:2:41320)

**Comment by simonbrowndotje** [comment]
I'd recommend (1) performing a hard refresh in case something is being cached or (2) updating to the latest version. Version `124.0.2478.51` works for me.

**Comment by thoni56** [comment]
Aaah, you mean update Edge! Couldn't get my head around the version number at first... ;-) I'll see what I can do.

BTW, there seems to be the something similar with Safari Version 17.4.1 (19618.1.15.11.14), showing "There is a problem loading your workspace - TypeError: undefined is not a constructor (evaluating 'new structurizr.Workspace(json)')". Again, Chrome displays things ok.

I can provide the console log for Safari too if you want.

**Comment by thoni56** [comment]
Right, so forcing Edge to really reload everything worked. Thanks.
