### ISSUE TITLE
Error in the latest Docker image

### ISSUE THREAD

**Issue by SaschaWeisenberger** [structurizr/lite#52]
### Description

just pulled the latest docker image and could not start the project. When I use the tag 3000 it works (didn't try all the version in between).
Didn't change anything since earlier when it worked, same compose file, same dsl file etc...

<details>
  <summary>Here is the log</summary>

  2023-03-31 12:08:31 2023-03-31T10:08:31.960Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : Starting StructurizrLite using Java 17.0.5 with PID 1 (/usr/local/structurizr-lite.war started by root in /)
2023-03-31 12:08:31 2023-03-31T10:08:31.965Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : No active profile set, falling back to 1 default profile: "default"
2023-03-31 12:08:36 2023-03-31T10:08:36.061Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : Started StructurizrLite in 4.58 seconds (process running for 5.297)
2023-03-31 12:08:36 2023-03-31T10:08:36.064Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : ***********************************************************************************
2023-03-31 12:08:36 2023-03-31T10:08:36.064Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     :   _____ _                   _              _          
2023-03-31 12:08:36 2023-03-31T10:08:36.064Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     :  / ____| |                 | |            (_)         
2023-03-31 12:08:36 2023-03-31T10:08:36.064Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : | (___ | |_ _ __ _   _  ___| |_ _   _ _ __ _ _____ __ 
2023-03-31 12:08:36 2023-03-31T10:08:36.064Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     :  \___ \| __| '__| | | |/ __| __| | | | '__| |_  / '__|
2023-03-31 12:08:36 2023-03-31T10:08:36.064Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     :  ____) | |_| |  | |_| | (__| |_| |_| | |  | |/ /| |   
2023-03-31 12:08:36 2023-03-31T10:08:36.064Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : |_____/ \__|_|   \__,_|\___|\__|\__,_|_|  |_/___|_|   
2023-03-31 12:08:36 2023-03-31T10:08:36.064Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     :                                                       
2023-03-31 12:08:36 2023-03-31T10:08:36.064Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : Structurizr Lite
2023-03-31 12:08:36 2023-03-31T10:08:36.066Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     :  - build: 3041 (2023-03-31T08:35:17Z
2023-03-31 12:08:36 2023-03-31T10:08:36.066Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     :  - structurizr-java: v1.24.0
2023-03-31 12:08:36 2023-03-31T10:08:36.074Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     :  - structurizr-dsl: v1.30.0
2023-03-31 12:08:36 2023-03-31T10:08:36.075Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     :  - structurizr-import: v1.4.1
2023-03-31 12:08:36 2023-03-31T10:08:36.075Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : 
2023-03-31 12:08:36 2023-03-31T10:08:36.075Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : Workspace path: /usr/local/structurizr
2023-03-31 12:08:36 2023-03-31T10:08:36.075Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : Workspace filename: workspace[.dsl|.json]
2023-03-31 12:08:36 2023-03-31T10:08:36.075Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : URL: 
2023-03-31 12:08:36 2023-03-31T10:08:36.076Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : Auto-save interval: 5000ms
2023-03-31 12:08:36 2023-03-31T10:08:36.076Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : Auto-refresh interval: 0ms
2023-03-31 12:08:36 2023-03-31T10:08:36.084Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : dot: available
2023-03-31 12:08:36 2023-03-31T10:08:36.084Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : ***********************************************************************************
2023-03-31 12:08:36 2023-03-31T10:08:36.084Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : MIT License
2023-03-31 12:08:36 2023-03-31T10:08:36.085Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : 
2023-03-31 12:08:36 2023-03-31T10:08:36.085Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : Copyright (c) 2023 Structurizr Limited
2023-03-31 12:08:36 2023-03-31T10:08:36.085Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : 
2023-03-31 12:08:36 2023-03-31T10:08:36.085Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : Permission is hereby granted, free of charge, to any person obtaining a copy
2023-03-31 12:08:36 2023-03-31T10:08:36.085Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : of this software and associated documentation files (the "Software"), to deal
2023-03-31 12:08:36 2023-03-31T10:08:36.085Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : in the Software without restriction, including without limitation the rights
2023-03-31 12:08:36 2023-03-31T10:08:36.085Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
2023-03-31 12:08:36 2023-03-31T10:08:36.085Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : copies of the Software, and to permit persons to whom the Software is
2023-03-31 12:08:36 2023-03-31T10:08:36.085Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : furnished to do so, subject to the following conditions:
2023-03-31 12:08:36 2023-03-31T10:08:36.085Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : 
2023-03-31 12:08:36 2023-03-31T10:08:36.085Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : The above copyright notice and this permission notice shall be included in all
2023-03-31 12:08:36 2023-03-31T10:08:36.085Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : copies or substantial portions of the Software.
2023-03-31 12:08:36 2023-03-31T10:08:36.086Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : 
2023-03-31 12:08:36 2023-03-31T10:08:36.086Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
2023-03-31 12:08:36 2023-03-31T10:08:36.086Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
2023-03-31 12:08:36 2023-03-31T10:08:36.086Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
2023-03-31 12:08:36 2023-03-31T10:08:36.086Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
2023-03-31 12:08:36 2023-03-31T10:08:36.086Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
2023-03-31 12:08:36 2023-03-31T10:08:36.086Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
2023-03-31 12:08:36 2023-03-31T10:08:36.086Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : SOFTWARE.
2023-03-31 12:08:36 2023-03-31T10:08:36.086Z  INFO 1 --- [           main] com.structurizr.lite.StructurizrLite     : ***********************************************************************************
2023-03-31 12:08:39 2023-03-31T10:08:39.940Z  WARN 1 --- [nio-8080-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Failure in @ExceptionHandler com.structurizr.lite.web.ApiController#error(HttpServletResponse, String)
2023-03-31 12:08:39 
2023-03-31 12:08:39 java.lang.IllegalStateException: Could not resolve parameter [1] in public com.structurizr.lite.web.ApiResponse com.structurizr.lite.web.ApiController.error(jakarta.servlet.http.HttpServletResponse,java.lang.String): No suitable resolver
2023-03-31 12:08:39 at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:178) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:148) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:413) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:74) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:141) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:80) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1341) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1152) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1098) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705) ~[tomcat-embed-core-10.1.5.jar!/:6.0.0]
2023-03-31 12:08:39 at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814) ~[tomcat-embed-core-10.1.5.jar!/:6.0.0]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
2023-03-31 12:08:39 
2023-03-31 12:08:39 2023-03-31T10:08:39.945Z ERROR 1 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoSuchMethodError: 'java.util.Set com.structurizr.documentation.Documentation.getSections()'] with root cause
2023-03-31 12:08:39 
2023-03-31 12:08:39 java.lang.NoSuchMethodError: 'java.util.Set com.structurizr.documentation.Documentation.getSections()'
2023-03-31 12:08:39 at com.structurizr.dsl.plugins.mermaid.MermaidEncoderPlugin.run(MermaidEncoderPlugin.java:22) ~[na:na]
2023-03-31 12:08:39 at com.structurizr.dsl.PluginDslContext.end(PluginDslContext.java:28) ~[structurizr-dsl-1.30.0.jar!/:1.30.0]
2023-03-31 12:08:39 at com.structurizr.dsl.StructurizrDslParser.endContext(StructurizrDslParser.java:964) ~[structurizr-dsl-1.30.0.jar!/:1.30.0]
2023-03-31 12:08:39 at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:848) ~[structurizr-dsl-1.30.0.jar!/:1.30.0]
2023-03-31 12:08:39 at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:128) ~[structurizr-dsl-1.30.0.jar!/:1.30.0]
2023-03-31 12:08:39 at com.structurizr.lite.component.workspace.FileSystemWorkspaceComponentImpl.loadWorkspaceFromDsl(FileSystemWorkspaceComponentImpl.java:122) ~[classes!/:na]
2023-03-31 12:08:39 at com.structurizr.lite.component.workspace.FileSystemWorkspaceComponentImpl.loadWorkspace(FileSystemWorkspaceComponentImpl.java:88) ~[classes!/:na]
2023-03-31 12:08:39 at com.structurizr.lite.component.workspace.FileSystemWorkspaceComponentImpl.getWorkspace(FileSystemWorkspaceComponentImpl.java:156) ~[classes!/:na]
2023-03-31 12:08:39 at com.structurizr.lite.web.ApiController.getWorkspace(ApiController.java:37) ~[classes!/:na]
2023-03-31 12:08:39 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2023-03-31 12:08:39 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2023-03-31 12:08:39 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2023-03-31 12:08:39 at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
2023-03-31 12:08:39 at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705) ~[tomcat-embed-core-10.1.5.jar!/:6.0.0]
2023-03-31 12:08:39 at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814) ~[tomcat-embed-core-10.1.5.jar!/:6.0.0]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.6.jar!/:6.0.6]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.5.jar!/:na]
2023-03-31 12:08:39 at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
2023-03-31 12:08:39 

</details>

### Steps to reproduce

run `docker compose up -d` with 
```yml
version: '3.3'
services:
  structurizer:
    container_name: structurizr
    pull_policy: always
    image: structurizr/lite:latest
    ports:
      - 8080:8080
    volumes:
      - .:/usr/local/structurizr
    restart: always
```

### Severity

Critical

### Priority

Low

### Resolution

I have no budget, please fix this for free

**Comment by simonbrowndotje** [comment]
I suspect the `MermaidEncoderPlugin` that you're using needs rebuilding.

**Comment by SaschaWeisenberger** [comment]
I disabled the Plugin and the rest worked fine again. Thanks for that hint!
